language: java
sudo: false
dist: trusty
arch: ppc64le
os: linux
jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
    - libcppunit-dev protobuf-compiler

script:
  - protoc --version
  - mvn clean apache-rat:check install -DskipTests spotbugs:check checkstyle:check -Pfull-build

branches:
  only:
  - master
  - branch-3.5
  - branch-3.4
