language: java
sudo: false
arch: ppc64le
os: linux
dist: trusty
jdk: openjdk11

cache:
  directories:
  - "$HOME/.m2"

install: sudo apt-get install maven 

script: 
  - mvn clean install -DskipTests spotbugs:check
  - mvn test

branches:
  only:
  - branch-3.5.5

