language: java
sudo: false

matrix:
  include:
     arch: ppc64le
     os: linux-ppc64le
     jdk: openjdk11

cache:
  directories:
  - "$HOME/.m2"

install: sudo apt-get install maven 

script: 
  - mvn --version
  - mvn clean install -DskipTests spotbugs:check
  - mvn test

branches:
  only:
  - branch-3.5.5

